name: JTrader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test with pytest
        run: |
          cp docker-compose.override.yml.dist docker-compose.override.yml
          docker-compose run jtrader bash -c "make virtualenv && source env/bin/activate && make test"